### ISSUE TITLE
RuntimeError: cuda runtime error (59) & changing num_classes

### ISSUE THREAD

**Issue by walnutmandu** [zhangkaij/ssd300_coco#1]
I changed dataset(coco data from train2017 to train2014) and the annotation(coco_text.json).
also, I changed num_classes in train.py (num_classes=81 -> num_classes = 3) 
when I run the code in local PC with CPU, iterations go well until 600 iter.
But, when I run the code using GPU server, following error occurred.

 it there any solutions?

 File "trainTEXT.py", line 233, in <module>
    train()
  File "trainTEXT.py", line 184, in train
    loss_l, loss_c = criterion(out, targets)
  File "/home/nhnent/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/nhnent/H1/users/ocr/ssd300_coco/layers/modules/multibox_loss.py", line 105, in forward
    conf_p = conf_data[(pos_idx+neg_idx).gt(0)].view(-1,self.num_classes)
  File "/home/nhnent/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 74, in __getitem__
    return MaskedSelect.apply(self, key)
  File "/home/nhnent/anaconda3/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 465, in forward
    return tensor.masked_select(mask)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/generated/../THCReduceAll.cuh:339

**Comment by zhangkaij** [comment]
Some images in train dataset don't contain any ground truth object, and please filter out them.
What's more, my code can not maintain the same accuracy with the paper SSD, and I am debugging. 
probably it needs two or three days to solve this problem.

**Comment by walnutmandu** [comment]
Thank you! I solved the problem. 
The number of my object classes is 3, so I need to change num_classes from 3 to 4.
Plus, Because of using only one gpu, I commented line 77-78 in train.py below.

 #if args.cuda:
     #net = torch.nn.DataParallel(ssd_net)
Using DataParallel occurs bugs : not completing process like zombies.
